#########################
##      ChatterBot     ##
#########################

# Name displayed in ChatterBot's messages
ChatterBot-Name: [%ChatterBot-Name%]

# Format in which ChatterBot speaks
ChatterBot-Format: [%ChatterBot-Format%]

# Should messages players send ChatterBot be shown publicly?
Loud-Mode: [%Loud-Mode%]

# What is shown when a player asks ChatterBot a question (while on loud mode)
Loud-Format: [%Loud-Format%]

# ChatterBot will be assigned to a player for a certain amount of time if a trigger word is said
Trigger-Words: [%Trigger-Words%]

# How many seconds ChatterBot will be assigned to a player after they've said a trigger word
Trigger-Word-Timeout: [%Trigger-Word-Timeout%]

# List of words that enable ChatterBot when said in chat
Trigger-Word-List: [%Trigger-Word-List%]

# When the amount of players is below this amount ChatterBot is automatically enabled
# Set this to -1 to disable
Trigger-Player-Amount: [%Trigger-Player-Amount%]

# Change the type of bot ChatterBot uses
# Options:
# - CLEVERBOT
# - JABBERWACKY
ChatterBot-Type: [%ChatterBot-Type%]

# Delayed responses help combat players using the bot to cause spam
#
# Chatterbot will pick a random amount of time between the minimum and maximum and
# wait that long before responding (not accounting for the time it takes for the bot to think)
# Set this to false to disable this feature
Delayed-Response-Enabled: [%Delayed-Response-Enabled%]

# The minimum amount of time Chatterbot would ever take to respond
Delayed-Minimum-Seconds: [%Delayed-Minimum-Seconds%]

# The maximum amount of time Chatterbot would ever take to respond
Delayed-Maximum-Seconds: [%Delayed-Maximum-Seconds%]